services:
  db:
    image: postgres:17
    container_name: futebol_postgres
    environment:
      POSTGRES_USER: futebol
      POSTGRES_PASSWORD: futebol
      POSTGRES_DB: futebol
    ports:
      - "5435:5432"
    volumes:
      - futebol_pgdata:/var/lib/postgresql/data

volumes:
  futebol_pgdata:
